"""Normative desktop v0.2 capture-package resource limits."""

MIB = 1024 * 1024

SUPPORTED_SCHEMA = "coin-analyzer.capture-package"
SUPPORTED_SCHEMA_VERSION = "1.0"
JOURNAL_SCHEMA_VERSION = "1.0"
LEGACY_JOURNAL_SCHEMA_VERSION = JOURNAL_SCHEMA_VERSION
DURABLE_JOURNAL_SCHEMA_VERSION = "2.0"
TERMINAL_HISTORY_SCHEMA_VERSION = "1.0"
RETIREMENT_MANIFEST_SCHEMA_VERSION = "1.0"
AUDIT_SCHEMA_VERSION = "1.0"
IMPORT_LOCK_SCHEMA_VERSION = "1.0"
SNAPSHOT_SCHEMA_VERSION = "1.0"
PROCESSED_SNAPSHOT_OWNER_SCHEMA_VERSION = "1.0"
PROCESSED_SNAPSHOT_MANIFEST_SCHEMA_VERSION = "1.0"
PROCESSED_SNAPSHOT_COMPLETION_SCHEMA_VERSION = "1.0"
MISSING_COLLECTION_SENTINEL = "MISSING_COLLECTION_V1"
MAX_LOCK_WAIT_SECONDS = 30.0
MAX_LOCK_POLL_SECONDS = 1.0
MAX_JOURNAL_GENERATIONS = 4096
MAX_NORMAL_JOURNAL_GENERATION = 3583
FIRST_CLOSURE_RESERVE_GENERATION = 3584
MAX_IMPORT_STATE_MEMBERS = 10_000

MAX_PACKAGE_SIZE = 256 * MIB
MAX_ARCHIVE_ENTRIES = 256
MAX_COINS_PER_PACKAGE = 100
MAX_IMAGES_PER_COIN = 3
MAX_JSON_BYTES = 1 * MIB
MAX_MANIFEST_SIZE = MAX_JSON_BYTES
MAX_COMPRESSED_ENTRY_SIZE = 40 * MIB
MAX_IMAGE_SIZE = 40 * MIB
MAX_TOTAL_UNCOMPRESSED_SIZE = 256 * MIB
MAX_COMPRESSION_RATIO = 100
MAX_IMAGE_DIMENSION = 12_000
MAX_IMAGE_PIXELS = 80_000_000
MAX_PROCESSED_ARTIFACTS = 300
MAX_PROCESSED_ARTIFACT_SIZE = 40 * MIB
MAX_PROCESSED_ARTIFACT_BYTES = 256 * MIB
MAX_SAFE_RELATIVE_PATH_CHARS = 1024

MAX_JSON_NESTING = 8
MAX_KEYS_PER_OBJECT = 64
MAX_STRING_CHARS = 16_384
MAX_AGGREGATE_STRING_CHARS = 262_144
MAX_DUPLICATE_EXISTING_ITEMS = 5_000
MAX_DUPLICATE_AUDITS = 1_000
MAX_DUPLICATE_MATCHED_IDS = 10
MAX_DUPLICATE_REASONS = 4
MAX_SAFE_INTEGER = (2**53) - 1
MAX_QUANTITY = 1_000_000
MAX_DECIMAL_CHARS = 64

SUPPORTED_IMAGE_TYPES = frozenset({"image/jpeg", "image/png"})
SUPPORTED_IMAGE_EXTENSIONS = frozenset({".jpg", ".png"})
